### ISSUE TITLE
Add Animal creation guide

### ISSUE THREAD

**Issue by jerometwell** [jerometwell/chimerify#3]
#2 has a guide for creating animals. Can we expand on this and make it a guide IN the project itself?

**Comment by Adam-STaC-Solutions** [comment]
As part of this, is it worth splitting the animal data into a separate or multiple json files to be loaded dynamically?

**Comment by Adam-STaC-Solutions** [comment]
Is it also worth adding run notes to the readme for windows?

this seems to be
>node index [animal1] [animal2]

**Comment by jerometwell** [comment]
100% on board with hot-loadable animals!
It would be nice if the animal data was consolidated. the format could change a lot - i'm open to ideas here. 

As for CLI, you should be using `npm link` to test installed packages, then you can use what the docs suggest: `chimera dog pig`. This will matter less when i get it on npm 👀

**Comment by Adam-STaC-Solutions** [comment]
Happy to create new tickets if these are going to to make this one bloated.

**Comment by jerometwell** [comment]
Closing as this has been merged!
